spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: set schema ''
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: disc
  mail:
    host: smtps.uhserver.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
  jackson:
    serialization:
      fail-on-empty-beans: false


jwt:
  secret: ${JWT_SECRET:8eZblrmNXm5pnhLugQ2QcyigTttKVPUqakljsdfufnwkutg}
  expiration: 86400000
  email:
    expiration: 86400000


server:
  port: 8080