insert into disc.roles (role_name) values ('ADMIN');
insert into disc.roles (role_name) values ('USER');
insert into disc.roles (role_name) values ('VERIFIED_USER');
insert into disc.state (name) values ('São Paulo');
insert into disc.city (name, state_id) values ('São Paulo', 1);
insert into disc.city (name, state_id) values ('São Bernardo do Campo', 1);
insert into disc.city (name, state_id) values ('Mogi das Cruzes', 1);
insert into disc.education_level (education_level) values('Cursando Ensino Médio');
insert into disc.education_level (education_level) values('Ensino Médio Completo');
insert into disc.education_level (education_level) values('Cursando Ensino Superior');
insert into disc.education_level (education_level) values('Ensino Superior Completo');
insert into disc.field_of_interest (field) values ('Desenvolvimento de software');
insert into disc.field_of_interest (field) values ('Psicologia');

insert into disc.tests (name) values ('persona01');

insert into disc.questions (question, test_id) values ('Costumo agir de maneira:', 1);
insert into disc.questions (question, test_id) values ('Quando em situações de atrito, busco:', 1);
insert into disc.questions (question, test_id) values ('Em meu dia a dia preciso de:', 1);
insert into disc.questions (question, test_id) values ('Inicialmente costumo ser:', 1);
insert into disc.questions (question, test_id) values ('Quando lido com situações de atrasos ou demora, eu:', 1);
insert into disc.questions (question, test_id) values ('Me sinto bem ao:', 1);
insert into disc.questions (question, test_id) values ('As pessoas me vêm como:', 1);
insert into disc.questions (question, test_id) values ('Minha principal dificuldade é ser:', 1);
insert into disc.questions (question, test_id) values ('Outra dificuldade em meu perfil é ser: ', 1);
insert into disc.questions (question, test_id) values ('Frente a situações difíceis:', 1);
insert into disc.questions (question, test_id) values ('Gosto de:', 1);
insert into disc.questions (question, test_id) values ('Quando alguém erra:', 1);
insert into disc.questions (question, test_id) values ('Minha maior preocupação é:', 1);
insert into disc.questions (question, test_id) values ('Não gosto de:', 1);
insert into disc.questions (question, test_id) values ('Pontos de Melhoria:', 1);
insert into disc.questions (question, test_id) values ('Em situações estressantes posso ser:', 1);
insert into disc.questions (question, test_id) values ('Em situações estressantes também posso ser:', 1);
insert into disc.questions (question, test_id) values ('Sei que me desempenhei bem, quando:', 1);
insert into disc.questions (question, test_id) values ('Também calculo meu desempenho por meio de:', 1);
insert into disc.questions (question, test_id) values ('Durante debates quero:', 1);
insert into disc.questions (question, test_id) values ('Principal qualidade:', 1);
insert into disc.questions (question, test_id) values ('Podem me achar:', 1);
insert into disc.questions (question, test_id) values ('Com colegas de trabalho, sou:', 1);
insert into disc.questions (question, test_id) values ('Em meu dia a dia, prefiro:', 1);
insert into disc.questions (question, test_id) values ('Quando saio para comprar coisas:', 1);

insert into disc.answers (answer, factor, question_id) values ('Direta', 'D', 1);
insert into disc.answers (answer, factor, question_id) values ('Convincente', 'I', 1);
insert into disc.answers (answer, factor, question_id) values ('Tranquila', 'S', 1);
insert into disc.answers (answer, factor, question_id) values ('Cuidadosa', 'C', 1);

insert into disc.answers (answer, factor, question_id) values ('Agir', 'D', 2);
insert into disc.answers (answer, factor, question_id) values ('Afrontar', 'I', 2);
insert into disc.answers (answer, factor, question_id) values ('Queixar', 'S', 2);
insert into disc.answers (answer, factor, question_id) values ('Esquivar', 'C', 2);

insert into disc.answers (answer, factor, question_id) values ('Controle', 'D', 3);
insert into disc.answers (answer, factor, question_id) values ('Validação', 'I', 3);
insert into disc.answers (answer, factor, question_id) values ('Hábitos', 'S', 3);
insert into disc.answers (answer, factor, question_id) values ('Parâmetros', 'C', 3);

insert into disc.answers (answer, factor, question_id) values ('Autossuficiente', 'D', 4);
insert into disc.answers (answer, factor, question_id) values ('Relacional', 'I', 4);
insert into disc.answers (answer, factor, question_id) values ('Constante', 'S', 4);
insert into disc.answers (answer, factor, question_id) values ('Crítico', 'C', 4);

insert into disc.answers (answer, factor, question_id) values ('Confronto', 'D', 5);
insert into disc.answers (answer, factor, question_id) values ('Negocio', 'I', 5);
insert into disc.answers (answer, factor, question_id) values ('Aceito', 'S', 5);
insert into disc.answers (answer, factor, question_id) values ('Reclamo', 'C', 5);

insert into disc.answers (answer, factor, question_id) values ('Tomar decisões', 'D', 6);
insert into disc.answers (answer, factor, question_id) values ('Relacionar-me socialmente', 'I', 6);
insert into disc.answers (answer, factor, question_id) values ('Trabalhar em equipe', 'S', 6);
insert into disc.answers (answer, factor, question_id) values ('Organizar e Programar', 'C', 6);

insert into disc.answers (answer, factor, question_id) values ('Resolvedor de problemas', 'D', 7);
insert into disc.answers (answer, factor, question_id) values ('Incentivador', 'I', 7);
insert into disc.answers (answer, factor, question_id) values ('Acolhedor', 'S', 7);
insert into disc.answers (answer, factor, question_id) values ('Planejador', 'C', 7);

insert into disc.answers (answer, factor, question_id) values ('Muito objetivo', 'D', 8);
insert into disc.answers (answer, factor, question_id) values ('Atrapalhado', 'I', 8);
insert into disc.answers (answer, factor, question_id) values ('Pouco Direto', 'S', 8);
insert into disc.answers (answer, factor, question_id) values ('Metódico', 'C', 8);

insert into disc.answers (answer, factor, question_id) values ('Intenso', 'D', 9);
insert into disc.answers (answer, factor, question_id) values ('Alternativo', 'I', 9);
insert into disc.answers (answer, factor, question_id) values ('Ambíguo', 'S', 9);
insert into disc.answers (answer, factor, question_id) values ('Impessoal', 'C', 9);

insert into disc.answers (answer, factor, question_id) values ('Foco no objetivo final', 'D', 10);
insert into disc.answers (answer, factor, question_id) values ('Falo o que vem a mente', 'I', 10);
insert into disc.answers (answer, factor, question_id) values ('Adio o contato com a situação', 'S', 10);
insert into disc.answers (answer, factor, question_id) values ('Foco em Analisar a situação', 'C', 10);

insert into disc.answers (answer, factor, question_id) values ('Multiplas coisas', 'D', 11);
insert into disc.answers (answer, factor, question_id) values ('Mais liberdade', 'I', 11);
insert into disc.answers (answer, factor, question_id) values ('Equilíbrio', 'S', 11);
insert into disc.answers (answer, factor, question_id) values ('Conhecimentos lógicos', 'C', 11);

insert into disc.answers (answer, factor, question_id) values ('Vou direto ao ponto', 'D', 12);
insert into disc.answers (answer, factor, question_id) values ('Explico sobre o erro para a pessoa', 'I', 12);
insert into disc.answers (answer, factor, question_id) values ('Prefiro não falar', 'S', 12);
insert into disc.answers (answer, factor, question_id) values ('Procuro entender o motivo do erro', 'C', 12);

insert into disc.answers (answer, factor, question_id) values ('Fracassar', 'D', 13);
insert into disc.answers (answer, factor, question_id) values ('Não ser aceito pelas pessoas', 'I', 13);
insert into disc.answers (answer, factor, question_id) values ('Mudanças repentidas', 'S', 13);
insert into disc.answers (answer, factor, question_id) values ('Cometer Erros', 'C', 13);

insert into disc.answers (answer, factor, question_id) values ('Ser criticado', 'D', 14);
insert into disc.answers (answer, factor, question_id) values ('Cumprir agendas', 'I', 14);
insert into disc.answers (answer, factor, question_id) values ('Ter que mudar', 'S', 14);
insert into disc.answers (answer, factor, question_id) values ('Tomar decisões repentinas', 'C', 14);

insert into disc.answers (answer, factor, question_id) values ('Manter a calma e empatizar', 'D', 15);
insert into disc.answers (answer, factor, question_id) values ('Lidar com emoções', 'I', 15);
insert into disc.answers (answer, factor, question_id) values ('Ser mais direto', 'S', 15);
insert into disc.answers (answer, factor, question_id) values ('Menos excesso de preocupação', 'C', 15);

insert into disc.answers (answer, factor, question_id) values ('Autoritário', 'D', 16);
insert into disc.answers (answer, factor, question_id) values ('Irônico', 'I', 16);
insert into disc.answers (answer, factor, question_id) values ('Obediente', 'S', 16);
insert into disc.answers (answer, factor, question_id) values ('Questionador', 'C', 16);

insert into disc.answers (answer, factor, question_id) values ('Julgador', 'D', 17);
insert into disc.answers (answer, factor, question_id) values ('Raso', 'I', 17);
insert into disc.answers (answer, factor, question_id) values ('Indeciso', 'S', 17);
insert into disc.answers (answer, factor, question_id) values ('Teimoso', 'C', 17);

insert into disc.answers (answer, factor, question_id) values ('Supero o objetivo', 'D', 18);
insert into disc.answers (answer, factor, question_id) values ('Recebo elogios', 'I', 18);
insert into disc.answers (answer, factor, question_id) values ('Consigo atingir ou me aproximar do objetivo', 'S', 18);
insert into disc.answers (answer, factor, question_id) values ('O resultado é preciso / lógico', 'C', 18);

insert into disc.answers (answer, factor, question_id) values ('Superação pessoal', 'D', 19);
insert into disc.answers (answer, factor, question_id) values ('Reconhecimento social', 'I', 19);
insert into disc.answers (answer, factor, question_id) values ('Participação', 'S', 19);
insert into disc.answers (answer, factor, question_id) values ('Qualidade Final', 'C', 19);

insert into disc.answers (answer, factor, question_id) values ('Estar certo', 'D', 20);
insert into disc.answers (answer, factor, question_id) values ('Minimizar o atrito', 'I', 20);
insert into disc.answers (answer, factor, question_id) values ('Concordar', 'S', 20);
insert into disc.answers (answer, factor, question_id) values ('Apresentar dados lógicos', 'C', 20);

insert into disc.answers (answer, factor, question_id) values ('Sinceridade', 'D', 21);
insert into disc.answers (answer, factor, question_id) values ('Positividade', 'I', 21);
insert into disc.answers (answer, factor, question_id) values ('Prestativo', 'S', 21);
insert into disc.answers (answer, factor, question_id) values ('Organizado', 'C', 21);

insert into disc.answers (answer, factor, question_id) values ('Estressado', 'D', 22);
insert into disc.answers (answer, factor, question_id) values ('Incoveniente', 'I', 22);
insert into disc.answers (answer, factor, question_id) values ('Incerto', 'S', 22);
insert into disc.answers (answer, factor, question_id) values ('Medroso', 'C', 22);

insert into disc.answers (answer, factor, question_id) values ('Direto', 'D', 23);
insert into disc.answers (answer, factor, question_id) values ('Tolerante', 'I', 23);
insert into disc.answers (answer, factor, question_id) values ('Discreto', 'S', 23);
insert into disc.answers (answer, factor, question_id) values ('Cuidadoso', 'C', 23);

insert into disc.answers (answer, factor, question_id) values ('Ser desafiado', 'D', 24);
insert into disc.answers (answer, factor, question_id) values ('Lidar com pessoas', 'I', 24);
insert into disc.answers (answer, factor, question_id) values ('Ter uma rotina e previsibilidade', 'S', 24);
insert into disc.answers (answer, factor, question_id) values ('Estrutura e organização', 'C', 24);

insert into disc.answers (answer, factor, question_id) values ('Vou direto ao que preciso', 'D', 25);
insert into disc.answers (answer, factor, question_id) values ('Me distraio', 'I', 25);
insert into disc.answers (answer, factor, question_id) values ('Nunca sei o que levar', 'S', 25);
insert into disc.answers (answer, factor, question_id) values ('Fico de olho no custo-benefício', 'C', 25);


insert into disc.factor_combination_description (factor_combination, title, description) values ('Di', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('DS', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('DI', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Ds', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('di', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Dc', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('DC', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('D=C', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');


insert into disc.factor_combination_description (factor_combination, title, description) values ('Id', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('ID', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('id', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Is', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('IS', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Ic', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('IC', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');

insert into disc.factor_combination_description (factor_combination, title, description) values ('Sd', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('SD', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Si', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('SI', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Sc', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('SC', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');

insert into disc.factor_combination_description (factor_combination, title, description) values ('Cd', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('CD', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Ci', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('CI', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('Cs', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');
insert into disc.factor_combination_description (factor_combination, title, description) values ('CS', 'Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar, turpis lobortis pellentesque lobortis, felis metus porta leo, nec accumsan quam lorem ut magna. Donec tristique consectetur nulla, non iaculis sem tincidunt sit amet. Quisque a interdum nisl. Pellentesque commodo enim quis nulla interdum bibendum. Pellentesque a orci nec erat sagittis hendrerit nec sed tellus. Aliquam sed tellus vel eros fermentum tempor. Donec tincidunt arcu vel elit luctus porttitor. Sed posuere nulla a elit congue viverra. Pellentesque tincidunt pulvinar tortor vel placerat. Nunc tristique venenatis scelerisque. Fusce mollis sit amet dui ultricies pharetra. Donec augue lacus, sodales vel aliquam lobortis, rhoncus a enim. Suspendisse pharetra pulvinar enim, ac convallis tortor tincidunt quis.');

insert into disc.main_factor_description (factor, title, description, positive_points, improvement_points, keywords) values ('D', 'Dominância', 'São pessoas competitivas e determinadas, voltadas a atingir objetivos e a atuar com foco em entregas e resultados. Exigentes, racionais, com tendência a comportamentos autoritários, podem querer controlar e dominar tudo a sua volta. Geralmente, se comunicam de forma direta e franca, não pensam muito antes de falar, chegam a interromper os outros. Gostam de desafios e lidam melhor com tarefas do que com pessoas. São motivados por liberdade, autonomia, autoridade, crescimento e desafios. Podem passar a impressão de um perfil corajoso, imparável e obstinado; por outro lado, podem parecer arrogantes, argumentativos e agressivos.', 'Grande capacidade de iniciar coisas, foco em resultados e metas, competividade, capacidade para lidar com grandes desafios.', 'Dificuldade para ouvir, impaciência, excesso de controle e de debates, autoritarismo, pouco planejamento.', 'Aventura; Competição; Iniciativa; Determinação; Agressividade; Objetividade; Impaciência.');
insert into disc.main_factor_description (factor, title, description, positive_points, improvement_points, keywords) values ('I', 'Influência', 'São pessoas comunicativas e extrovertidas, voltadas à interação. Possuem grande facilidade para conhecer pessoas e ampliar a sua rede de contatos. Costumam se comunicar de forma alegre, são persuasivas e convincentes, ou seja. possuem facilidade para vender suas ideias. Gostam de lidar com pessoas e são motivadas por reconhecimento social e popularidade, sendo assim, preferem um ambiente de trabalho descontraído e leve. Podem passar a impressão de um perfil divertido, informal, popular; por outra lado, podem parecer superficiais, exagerados e até prolixos.', 'Criatividade, motivação de pessoas, trabalho em equipe, negociação, persuasão, bom humor.', 'Impulsividade, sentimentalismo, falta de atenção a detalhes, excesso de expressões faciais, falar demais, pouco planejamento.', 'Acolhimento; Calma; Cooperação; Consistência; Possessividade; Previsibilidade; Sistematização.');
insert into disc.main_factor_description (factor, title, description, positive_points, improvement_points, keywords) values ('S', 'Estabilidade', 'São pessoas tranquilas, com habilidade para ouvir e pensar antes de falar, são cooperativas e termimam o que começam. Possuem tendência à cautela, por isso, precisam de mais tempo do que os demais para concluir tarefas. Costumam se comunicar de forma indireta. educada, cordial e atenciosa. Gostam de pessoas e de estabilidade. Suas relações profissionais ou pessoais são de longa duração. São motivados por harmonia, identificação com o ambiente e com as pessoas, procedimentos estruturados, e valorização do seu compromisso e lealdade. Podem passar a impressão de calma e serenidade; por outro lado, podem parecer instrospectivos e resistentes a mudanças.', 'rabalho em equipe,  dedicação a uma causa ou liderança, paciência para atuar em situações complexas, terminar o que começa, saber ouvir.', 'Resistência a mudanças, pouca iniciativa, tensão para lidar com críticas, baixo senso de urgência, autonomia limitada.', 'Acolhimento; Calma; Cooperação; Consistência; Possessividade; Previsibilidade; Sistematização.');
insert into disc.main_factor_description (factor, title, description, positive_points, improvement_points, keywords) values ('C', 'Conformidade', 'São pessoas altamente voltadas a detalhes, precisão e qualidade, com forte tendência a exigir demais tanto de si, quanto dos outros. Buscam a perfeição e, por isso, tendem a focar demais no que pode dar errado. Tendem a um perfil mais instrospectivo e costumam se comunicar de forma direta e objetiva. No entanto, podem ser detalhistas ao falar de aspectos relacionados a procedimentos ou direcionamentos. Gostam de ambientes com normas e regras claras, e preferem atuar com tarefas do que com pessoas. São motivados por procedimentos estruturados, qualidade, tempo para pensar e agir, e acesso a informações. Podem ser vistos como pessoas preocupadas e pessismistas;  por outro lado, passam a impressão de indivíduos focados, estudiosos e cheios de conteúdo.', 'Pensamento crítico, altos padrões de qualidade, foco, cuidado e atenção a detalhes.', 'Analisar demais, excesso de críticas, exigência e preocupação, perfil retraído.', 'Análise; Cautela; Conformidade; Qualidade; Formalidade; Instrospecção; Exigência.');


